In [2]:
# =========================================================
# NOTEBOOK: 01_data_loading.ipynb
# =========================================================

# =========================================================
# STEP 1 — IMPORT LIBRARIES
# =========================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [ ]:
# =========================================================
# STEP 2 — LOAD DATASETS
# =========================================================

customers_df = pd.read_csv(r'C:\Users\niran\Desktop\AI_Ecommerce_Customer_Intelligence_Platform\data\raw\customers.csv')

orders_df = pd.read_csv(r'C:\Users\niran\Desktop\AI_Ecommerce_Customer_Intelligence_Platform\data\raw\orders.csv')

order_items_df = pd.read_csv(r'C:\Users\niran\Desktop\AI_Ecommerce_Customer_Intelligence_Platform\data\raw\order_items.csv')

products_df = pd.read_csv(r'C:\Users\niran\Desktop\AI_Ecommerce_Customer_Intelligence_Platform\data\raw\products.csv')

sellers_df = pd.read_csv(r'C:\Users\niran\Desktop\AI_Ecommerce_Customer_Intelligence_Platform\data\raw\sellers.csv')

payments_df = pd.read_csv(r'C:\Users\niran\Desktop\AI_Ecommerce_Customer_Intelligence_Platform\data\raw\order_payments.csv')

reviews_df = pd.read_csv(r'C:\Users\niran\Desktop\AI_Ecommerce_Customer_Intelligence_Platform\data\raw\order_reviews.csv')

geolocation_df = pd.read_csv(r'C:\Users\niran\Desktop\AI_Ecommerce_Customer_Intelligence_Platform\data\raw\geolocation.csv')

print("All Datasets Loaded Successfully")

All Datasets Loaded Successfully

In [4]:
# =========================================================
# STEP 3 — DATASET SHAPES
# =========================================================

print("\n================ DATASET SHAPES ================\n")

print('customers_df shape      :', customers_df.shape)
print('orders_df shape         :', orders_df.shape)
print('order_items_df shape    :', order_items_df.shape)
print('products_df shape       :', products_df.shape)
print('sellers_df shape        :', sellers_df.shape)
print('payments_df shape       :', payments_df.shape)
print('reviews_df shape        :', reviews_df.shape)
print('geolocation_df shape    :', geolocation_df.shape)

================ DATASET SHAPES ================

customers_df shape      : (1000000, 9)
orders_df shape         : (1000000, 8)
order_items_df shape    : (2199819, 8)
products_df shape       : (2000, 10)
sellers_df shape        : (500, 8)
payments_df shape       : (1149371, 5)
reviews_df shape        : (933748, 7)
geolocation_df shape    : (11500, 5)

In [5]:


# =========================================================
# STEP 4 — CHECK FIRST 5 ROWS
# =========================================================

print("\n================ CUSTOMERS DATA ================\n")
display(customers_df.head())

print("\n================ ORDERS DATA ================\n")
display(orders_df.head())

print("\n================ ORDER ITEMS DATA ================\n")
display(order_items_df.head())

print("\n================ PRODUCTS DATA ================\n")
display(products_df.head())

print("\n================ SELLERS DATA ================\n")
display(sellers_df.head())

print("\n================ PAYMENTS DATA ================\n")
display(payments_df.head())

print("\n================ REVIEWS DATA ================\n")
display(reviews_df.head())

print("\n================ GEOLOCATION DATA ================\n")
display(geolocation_df.head())

================ CUSTOMERS DATA ================

,customer_id,customer_unique_id,customer_name,customer_gender,customer_age,customer_zip_code_prefix,customer_city,customer_state,customer_segment
0,1e2e2881-a0eb-4cb0-829f-a566e810d05f,d45cdff2-5195-41e2-a0e5-6fe597e378dd,James Ramos,M,47,85037,Phoenix,AZ,Consumer
1,380b7418-308c-4bf7-b2bd-3ee446cb9ea6,35cee471-325e-4ad2-8e4e-7b169dc6df81,Brian Jackson,M,18,90060,Los Angeles,CA,Consumer
2,89b0d980-868f-478d-a63b-5fea5f265f4f,c820d3a4-edd4-4b32-9605-22d97dcc8e5e,Debra Jones,F,61,30398,Atlanta,GA,Consumer
3,336d14e6-a22f-4126-b2b7-fa64a2955b34,d3d86bff-2f03-4bec-9cbf-9a2f8f0d5783,Jamie Estrada,F,34,30352,Atlanta,GA,Consumer
4,340c9f9d-bb72-4bfa-a6aa-aa9c7c18a03f,35cee471-325e-4ad2-8e4e-7b169dc6df81,Brian Jackson,M,18,90060,Los Angeles,CA,Consumer

================ ORDERS DATA ================

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,720fd9e9-cdeb-4dec-a187-f71586eb085a,1e2e2881-a0eb-4cb0-829f-a566e810d05f,canceled,2025-12-27 07:07:20,2025-12-27 08:33:20,NaN,NaN,2026-01-04 08:33:20
1,c0142972-63fa-4af2-8070-f583ab769847,380b7418-308c-4bf7-b2bd-3ee446cb9ea6,delivered,2019-06-07 19:30:44,2019-06-08 05:08:44,2019-06-09 05:08:44,2019-06-14 05:08:44,2019-06-16 05:08:44
2,11bdf634-2b87-4d37-8d76-be1e7aff8f3b,89b0d980-868f-478d-a63b-5fea5f265f4f,delivered,2023-04-02 14:39:33,2023-04-02 23:42:33,2023-04-03 23:42:33,2023-04-08 23:42:33,2023-04-10 23:42:33
3,d29b58ad-af2a-47b4-9214-b2664fb1fdba,336d14e6-a22f-4126-b2b7-fa64a2955b34,delivered,2023-01-28 12:09:24,2023-01-28 15:26:24,2023-01-29 15:26:24,2023-02-02 15:26:24,2023-02-04 15:26:24
4,53fabbc8-fd4f-4c12-8af9-258db94dda6c,340c9f9d-bb72-4bfa-a6aa-aa9c7c18a03f,canceled,2019-06-05 22:33:47,2019-06-06 01:24:47,NaN,NaN,2019-06-16 01:24:47

================ ORDER ITEMS DATA ================

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,discount_rate
0,720fd9e9-cdeb-4dec-a187-f71586eb085a,1,89804d82-33a1-4558-8fa2-9b0252a2a406,36c2b043-ccf4-4d9c-a0bb-4b8d28737fd7,2025-12-30 07:07:20,916.90,45.47,0.0
1,720fd9e9-cdeb-4dec-a187-f71586eb085a,2,ac10b78c-342e-4b50-9ea9-bddde7db2e79,09936504-415b-4f90-a5b8-ad15a5be67d0,2025-12-30 07:07:20,817.14,172.48,0.0
2,720fd9e9-cdeb-4dec-a187-f71586eb085a,3,f18e6310-0e75-4b7f-bc20-90ac1e7bd466,7d336012-7101-4a66-b6bc-c269620d8df9,2025-12-30 07:07:20,37.04,94.98,0.0
3,c0142972-63fa-4af2-8070-f583ab769847,1,5816f107-b725-4c41-b794-298bf9669a41,91fe2cc8-51a5-4c79-9c12-cea5ae013f55,2019-06-10 19:30:44,917.98,27.42,0.0
4,c0142972-63fa-4af2-8070-f583ab769847,2,f4b3ce27-568d-4c33-9248-6c314635f80a,54165da9-b969-4d50-9b61-ffd0d8b4d731,2019-06-10 19:30:44,28.71,145.25,0.0

================ PRODUCTS DATA ================

,product_id,product_category_name,product_name,product_brand,product_weight_g,product_length_cm,product_height_cm,product_width_cm,cost,price
0,cdc4381f-fa67-41f2-a7d5-07f330097589,books,When successful medical beat,Vertex,661,18,19,9,22.45,42.42
1,1f0d68f8-18d7-47c6-8c73-ffd89a2a960a,auto,Pulse Seat Cover Kit (M231),Pulse,9662,52,12,25,124.84,148.16
2,f68621b0-8316-4cc4-9ba6-af209132acd6,electronics,Nova M247 Headphones,Nova,4287,12,18,15,704.26,843.43
3,9c065d67-038d-4dca-b60e-09f0dd3616b4,home_goods,Crest Vacuum - Modern,Crest,949,42,6,22,25.27,52.56
4,7c1b1caa-713e-4b45-82e3-3bdeb31b20c9,furniture,Nimbus Chair - Minimal,Nimbus,37558,124,11,8,458.03,767.55

================ SELLERS DATA ================

,seller_id,seller_company_name,seller_contact_name,seller_contact_gender,seller_contact_age,seller_zip_code_prefix,seller_city,seller_state
0,82787b9a-3c5a-476a-9f1b-a5fc7d98c8cf,Johnson LLC,Holly Mcdaniel,F,57,60633,Chicago,IL
1,75c29e4b-cc77-45c9-a3b6-7aa713f56126,Hicks LLC,Charles Casey,M,33,30339,Atlanta,GA
2,d2bc11e3-2a8f-4d16-9b04-8db5008730de,Briggs-Brown,Daniel Serrano,M,33,98193,Seattle,WA
3,aacb0fbc-8983-41b2-b9df-e2c35b8ff171,Flores LLC,Dillon Brooks Jr.,M,30,90056,Los Angeles,CA
4,098ae009-ca72-4820-8e53-6a279fa26e63,Sosa Ltd,Vanessa Stone,F,46,60615,Chicago,IL

================ PAYMENTS DATA ================

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,720fd9e9-cdeb-4dec-a187-f71586eb085a,1,paypal,1,2084.01
1,c0142972-63fa-4af2-8070-f583ab769847,1,credit_card,6,1406.07
2,11bdf634-2b87-4d37-8d76-be1e7aff8f3b,1,voucher,1,911.30
3,11bdf634-2b87-4d37-8d76-be1e7aff8f3b,2,credit_card,8,600.57
4,d29b58ad-af2a-47b4-9214-b2664fb1fdba,1,credit_card,11,170.73

================ REVIEWS DATA ================

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,0ba49642-47bb-4817-9cc2-bb9ded7de7c5,c0142972-63fa-4af2-8070-f583ab769847,5,Perfect,The quality is amazing. Delivery was quick.,2019-06-19 05:08:44,2019-06-19 07:08:44
1,4e540350-1d67-4f18-bfbb-66e45e16bbc5,11bdf634-2b87-4d37-8d76-be1e7aff8f3b,5,Good,The service is excellent. Super fast shipping.,2023-04-12 23:42:33,2023-04-13 01:42:33
2,9bf68eb6-676d-4759-956e-564b7b90410c,d29b58ad-af2a-47b4-9214-b2664fb1fdba,5,Perfect,The item is fantastic. Arrived early!,2023-02-08 15:26:24,2023-02-08 17:26:24
3,17619bc8-a922-4c55-9ea6-fb027511e2fb,3d4a035e-588c-4ebd-ab6c-bf06a38cff10,5,Great,The product is good. Delivery was quick.,2022-01-26 22:36:58,2022-01-27 00:36:58
4,e41030af-afab-41f7-9a28-0098de875634,d7537ba2-da79-4a25-abaa-0b9a28452645,5,Perfect,The item is fantastic. Super fast shipping.,2021-12-18 19:09:26,2021-12-18 21:09:26

================ GEOLOCATION DATA ================

,zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,10093,40.756378,-74.032669,New York,NY
1,10075,40.681693,-73.956079,New York,NY
2,10010,40.642143,-73.969978,New York,NY
3,10020,40.803845,-74.024706,New York,NY
4,10017,40.767948,-73.964183,New York,NY

In [6]:

# =========================================================
# STEP 5 — DATA TYPES
# =========================================================

print("\n================ DATA TYPES ================\n")

print("customers_df.dtypes:\n")
print(customers_df.dtypes)

print("\norders_df.dtypes:\n")
print(orders_df.dtypes)

print("\norder_items_df.dtypes:\n")
print(order_items_df.dtypes)

print("\nproducts_df.dtypes:\n")
print(products_df.dtypes)

print("\nsellers_df.dtypes:\n")
print(sellers_df.dtypes)

print("\npayments_df.dtypes:\n")
print(payments_df.dtypes)

print("\nreviews_df.dtypes:\n")
print(reviews_df.dtypes)

print("\ngeolocation_df.dtypes:\n")
print(geolocation_df.dtypes)

================ DATA TYPES ================

customers_df.dtypes:

customer_id                 object
customer_unique_id          object
customer_name               object
customer_gender             object
customer_age                 int64
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
customer_segment            object
dtype: object

orders_df.dtypes:

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

order_items_df.dtypes:

order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
discount_rate          float64
dtype: object

products_df.dtypes:

product_id                object
product_category_name     object
product_name              object
product_brand             object
product_weight_g           int64
product_length_cm          int64
product_height_cm          int64
product_width_cm           int64
cost                     float64
price                    float64
dtype: object

sellers_df.dtypes:

seller_id                 object
seller_company_name       object
seller_contact_name       object
seller_contact_gender     object
seller_contact_age         int64
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

payments_df.dtypes:

order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

reviews_df.dtypes:

review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

geolocation_df.dtypes:

zip_code_prefix        int64
geolocation_lat      float64
geolocation_lng      float64
geolocation_city      object
geolocation_state     object
dtype: object

In [7]:

# =========================================================
# STEP 6 — DATE CONVERSION
# =========================================================

# -----------------------------
# ORDERS DATE COLUMNS
# -----------------------------

orders_date_cols = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]

for col in orders_date_cols:
    orders_df[col] = pd.to_datetime(
        orders_df[col],
        errors='coerce'
    )


# -----------------------------
# ORDER ITEMS DATE COLUMNS
# -----------------------------

order_items_date_cols = [
    'shipping_limit_date'
]

for col in order_items_date_cols:
    order_items_df[col] = pd.to_datetime(
        order_items_df[col],
        errors='coerce'
    )


# -----------------------------
# REVIEWS DATE COLUMNS
# -----------------------------

reviews_date_cols = [
    'review_creation_date',
    'review_answer_timestamp'
]

for col in reviews_date_cols:
    reviews_df[col] = pd.to_datetime(
        reviews_df[col],
        errors='coerce'
    )

print("\nDate Columns Converted Successfully")

Date Columns Converted Successfully

In [8]:

# =========================================================
# STEP 7 — VERIFY UPDATED DATA TYPES
# =========================================================

print("\n================ UPDATED DATA TYPES ================\n")

print("\norders_df.dtypes:\n")
print(orders_df.dtypes)

print("\norder_items_df.dtypes:\n")
print(order_items_df.dtypes)

print("\nreviews_df.dtypes:\n")
print(reviews_df.dtypes)

================ UPDATED DATA TYPES ================


orders_df.dtypes:

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

order_items_df.dtypes:

order_id                       object
order_item_id                   int64
product_id                     object
seller_id                      object
shipping_limit_date    datetime64[ns]
price                         float64
freight_value                 float64
discount_rate                 float64
dtype: object

reviews_df.dtypes:

review_id                          object
order_id                           object
review_score                        int64
review_comment_title               object
review_comment_message             object
review_creation_date       datetime64[ns]
review_answer_timestamp    datetime64[ns]
dtype: object

In [9]:

# =========================================================
# STEP 8 — CHECK MISSING VALUES
# =========================================================

print("\n================ MISSING VALUES ================\n")

datasets = {
    'customers_df': customers_df,
    'orders_df': orders_df,
    'order_items_df': order_items_df,
    'products_df': products_df,
    'sellers_df': sellers_df,
    'payments_df': payments_df,
    'reviews_df': reviews_df,
    'geolocation_df': geolocation_df
}

for name, df in datasets.items():

    print(f"\n{name}")
    print("-" * 50)

    missing = df.isnull().sum()

    missing = missing[missing > 0]

    if len(missing) == 0:
        print("No Missing Values")
    else:
        print(missing.sort_values(ascending=False))

================ MISSING VALUES ================


customers_df
--------------------------------------------------
No Missing Values

orders_df
--------------------------------------------------
order_delivered_carrier_date     66252
order_delivered_customer_date    66252
dtype: int64

order_items_df
--------------------------------------------------
No Missing Values

products_df
--------------------------------------------------
No Missing Values

sellers_df
--------------------------------------------------
No Missing Values

payments_df
--------------------------------------------------
No Missing Values

reviews_df
--------------------------------------------------
No Missing Values

geolocation_df
--------------------------------------------------
No Missing Values

In [10]:

# =========================================================
# STEP 9 — CHECK DUPLICATES
# =========================================================

print("\n================ DUPLICATE RECORDS ================\n")

for name, df in datasets.items():

    duplicate_count = df.duplicated().sum()

    print(f"{name} --> Duplicate Rows: {duplicate_count}")

================ DUPLICATE RECORDS ================

customers_df --> Duplicate Rows: 0
orders_df --> Duplicate Rows: 0
order_items_df --> Duplicate Rows: 0
products_df --> Duplicate Rows: 0
sellers_df --> Duplicate Rows: 0
payments_df --> Duplicate Rows: 0
reviews_df --> Duplicate Rows: 0
geolocation_df --> Duplicate Rows: 0

In [11]:

# =========================================================
# STEP 10 — BASIC STATISTICAL SUMMARY
# =========================================================

print("\n================ NUMERICAL SUMMARY ================\n")

display(customers_df.describe())

display(order_items_df.describe())

display(products_df.describe())

display(payments_df.describe())

display(reviews_df.describe())

================ NUMERICAL SUMMARY ================

         customer_age  customer_zip_code_prefix
count  1000000.000000            1000000.000000
mean        35.383124              57314.170948
std         11.219629              30624.162507
min         18.000000              10010.000000
25%         27.000000              30369.000000
50%         35.000000              77012.000000
75%         43.000000              90019.000000
max         70.000000              98199.000000

,order_item_id,shipping_limit_date,price,freight_value,discount_rate
count,2.199819e+06,2199819,2.199819e+06,2.199819e+06,2.199819e+06
mean,1.847999e+00,2023-08-02 23:35:02.771228160,4.469182e+02,1.086660e+02,1.723830e-02
min,1.000000e+00,2019-01-04 01:21:03,1.001000e+01,5.060000e+00,0.000000e+00
25%,1.000000e+00,2022-07-06 19:55:16.500000,6.409000e+01,6.459000e+01,0.000000e+00
50%,2.000000e+00,2024-01-29 14:28:09,1.765900e+02,1.056700e+02,0.000000e+00
75%,2.000000e+00,2025-03-05 09:37:35,7.365900e+02,1.593700e+02,0.000000e+00
max,6.000000e+00,2026-01-03 23:59:31,1.999850e+03,2.502900e+02,3.000000e-01
std,9.723012e-01,NaN,5.398570e+02,6.387854e+01,5.864699e-02

,product_weight_g,product_length_cm,product_height_cm,product_width_cm,cost,price
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000
mean,6555.015000,48.938500,16.744500,16.810000,223.647330,322.65161
std,10777.216718,43.596801,7.294095,7.085337,339.807816,419.82025
min,100.000000,5.000000,5.000000,5.000000,4.430000,10.01000
25%,608.750000,19.000000,10.000000,11.000000,23.552500,45.48750
50%,1424.000000,33.000000,17.000000,17.000000,73.470000,150.92500
75%,6175.500000,62.000000,23.000000,23.000000,275.747500,404.58750
max,49869.000000,199.000000,29.000000,29.000000,1693.120000,1999.85000

       payment_sequential  payment_installments  payment_value
count        1.149371e+06          1.149371e+06   1.149371e+06
mean         1.129959e+00          3.949850e+00   1.063351e+03
std          3.362584e-01          3.732548e+00   9.637454e+02
min          1.000000e+00          1.000000e+00   1.555000e+01
25%          1.000000e+00          1.000000e+00   3.258300e+02
50%          1.000000e+00          1.000000e+00   7.453900e+02
75%          1.000000e+00          7.000000e+00   1.560080e+03
max          2.000000e+00          1.200000e+01   1.105452e+04

,review_score,review_creation_date,review_answer_timestamp
count,933748.000000,933748,933748
mean,4.034775,2023-08-02 01:47:20.129997824,2023-08-02 03:47:20.129998080
min,1.000000,2019-01-05 18:51:36,2019-01-05 20:51:36
25%,4.000000,2022-07-05 19:18:55,2022-07-05 21:18:55
50%,5.000000,2024-01-26 05:33:52,2024-01-26 07:33:52
75%,5.000000,2025-02-28 16:15:02.750000128,2025-02-28 18:15:02.750000128
max,5.000000,2026-01-07 23:45:12,2026-01-08 01:45:12
std,1.229050,NaN,NaN

In [12]:

# =========================================================
# STEP 11 — BASIC BUSINESS KPIs
# =========================================================

print("\n================ BUSINESS KPIs ================\n")

# Total Customers
total_customers = customers_df['customer_unique_id'].nunique()

# Total Orders
total_orders = orders_df['order_id'].nunique()

# Total Products
total_products = products_df['product_id'].nunique()

# Total Sellers
total_sellers = sellers_df['seller_id'].nunique()

# Total Revenue
total_revenue = payments_df['payment_value'].sum()

# Average Order Value
avg_order_value = payments_df['payment_value'].mean()

# Delivered Orders
delivered_orders = (
    orders_df['order_status'] == 'delivered'
).sum()

# Cancelled Orders
cancelled_orders = (
    orders_df['order_status'] == 'canceled'
).sum()

# Delivery Success Rate
delivery_success_rate = (
    delivered_orders / total_orders
) * 100

# Average Review Score
avg_review_score = reviews_df['review_score'].mean()

print(f"Total Customers           : {total_customers:,}")
print(f"Total Orders              : {total_orders:,}")
print(f"Total Products            : {total_products:,}")
print(f"Total Sellers             : {total_sellers:,}")
print(f"Total Revenue             : ${total_revenue:,.2f}")
print(f"Average Order Value       : ${avg_order_value:.2f}")
print(f"Delivered Orders          : {delivered_orders:,}")
print(f"Cancelled Orders          : {cancelled_orders:,}")
print(f"Delivery Success Rate     : {delivery_success_rate:.2f}%")
print(f"Average Review Score      : {avg_review_score:.2f}")

================ BUSINESS KPIs ================

Total Customers           : 279,199
Total Orders              : 1,000,000
Total Products            : 2,000
Total Sellers             : 500
Total Revenue             : $1,222,184,572.85
Average Order Value       : $1063.35
Delivered Orders          : 933,748
Cancelled Orders          : 66,252
Delivery Success Rate     : 93.37%
Average Review Score      : 4.03

In [13]:

# =========================================================
# STEP 12 — CREATE TIME FEATURES
# =========================================================

# Delivery Duration
orders_df['delivery_duration_days'] = (
    orders_df['order_delivered_customer_date']
    - orders_df['order_purchase_timestamp']
).dt.days

# Delivery Delay
orders_df['delivery_delay_days'] = (
    orders_df['order_delivered_customer_date']
    - orders_df['order_estimated_delivery_date']
).dt.days

# Approval Time
orders_df['approval_time_hours'] = (
    orders_df['order_approved_at']
    - orders_df['order_purchase_timestamp']
).dt.total_seconds() / 3600

# Purchase Features
orders_df['purchase_year'] = (
    orders_df['order_purchase_timestamp'].dt.year
)

orders_df['purchase_month'] = (
    orders_df['order_purchase_timestamp'].dt.month
)

orders_df['purchase_day'] = (
    orders_df['order_purchase_timestamp'].dt.day
)

orders_df['purchase_weekday'] = (
    orders_df['order_purchase_timestamp'].dt.day_name()
)

print("\nTime Features Created Successfully")

Time Features Created Successfully

In [14]:


# =========================================================
# STEP 13 — CHECK NEW FEATURES
# =========================================================

print("\n================ NEW TIME FEATURES ================\n")

display(
    orders_df[
        [
            'delivery_duration_days',
            'delivery_delay_days',
            'approval_time_hours',
            'purchase_year',
            'purchase_month',
            'purchase_day',
            'purchase_weekday'
        ]
    ].head()
)

================ NEW TIME FEATURES ================

,delivery_duration_days,delivery_delay_days,approval_time_hours,purchase_year,purchase_month,purchase_day,purchase_weekday
0,NaN,NaN,1.433333,2025,12,27,Saturday
1,6.0,-2.0,9.633333,2019,6,7,Friday
2,6.0,-2.0,9.050000,2023,4,2,Sunday
3,5.0,-2.0,3.283333,2023,1,28,Saturday
4,NaN,NaN,2.850000,2019,6,5,Wednesday

In [15]:

# =========================================================
# STEP 14 — UNDERSTAND TABLE RELATIONSHIPS
# =========================================================

print("\n================ TABLE RELATIONSHIPS ================\n")

print("""
customers_df
    └── customer_id
            ↓
orders_df
    └── order_id
            ↓
order_items_df
        ├── product_id → products_df
        └── seller_id  → sellers_df

orders_df
    ├── order_id → payments_df
    └── order_id → reviews_df
""")

================ TABLE RELATIONSHIPS ================


customers_df
    └── customer_id
            ↓
orders_df
    └── order_id
            ↓
order_items_df
        ├── product_id → products_df
        └── seller_id  → sellers_df

orders_df
    ├── order_id → payments_df
    └── order_id → reviews_df

In [16]:


# =========================================================
# STEP 15 — SAVE NOTEBOOK COMPLETION MESSAGE
# =========================================================

print("\n===================================================")
print("01_data_loading.ipynb COMPLETED SUCCESSFULLY")
print("===================================================")

===================================================
01_data_loading.ipynb COMPLETED SUCCESSFULLY
===================================================